name = "LiMetalPhaseFields"
uuid = "edd044fe-e47f-44cc-921d-3de31ffd016c"
authors = ["Brady Planden"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
